In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity


In [2]:

ds = pd.read_csv("./content-sample-data.csv")
print("The Dim of the data is: ", (ds.shape)) 


The Dim of the data is:  (500, 2)


In [3]:
ds.head

<bound method NDFrame.head of       id                                        description
0      1  Active classic boxers - There's a reason why o...
1      2  Active sport boxer briefs - Skinning up Glory ...
2      3  Active sport briefs - These superbreathable no...
3      4  Alpine guide pants - Skin in, climb ice, switc...
4      5  Alpine wind jkt - On high ridges, steep ice an...
..   ...                                                ...
495  496  Cap 2 bottoms - Cut loose from the maddening c...
496  497  Cap 2 crew - This crew takes the edge off fick...
497  498  All-time shell - No need to use that morning T...
498  499  All-wear cargo shorts - All-Wear Cargo Shorts ...
499  500  All-wear shorts - Time to simplify? Our All-We...

[500 rows x 2 columns]>

In [4]:

tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(ds['description'])



In [6]:
print("The Dim of tfidf_matrix is: ", (tfidf_matrix.shape)) 
print(tfidf_matrix)

print (tf.vocabulary_)

The Dim of tfidf_matrix is:  (500, 52262)
  (0, 5082)	0.04626380862294002
  (0, 31139)	0.011758800751191277
  (0, 1641)	0.07080059817388241
  (0, 50353)	0.07080059817388241
  (0, 5367)	0.07080059817388241
  (0, 5090)	0.011758800751191277
  (0, 18103)	0.046736221920387164
  (0, 9505)	0.046736221920387164
  (0, 30377)	0.04305091014250708
  (0, 29484)	0.04172689420704989
  (0, 18367)	0.04172689420704989
  (0, 33778)	0.05475768067155225
  (0, 35887)	0.05383138493531891
  (0, 15042)	0.02329084447698849
  (0, 5122)	0.015624497845885543
  (0, 5079)	0.011572518761001242
  (0, 47276)	0.011572518761001242
  (0, 25747)	0.011572518761001242
  (0, 40648)	0.0580868868522042
  (0, 21702)	0.0580868868522042
  (0, 24617)	0.04626380862294002
  (0, 24884)	0.03183250400752269
  (0, 5038)	0.07549285074439553
  (0, 46586)	0.07549285074439553
  (0, 25287)	0.06488905905925031
  :	:
  (499, 35955)	0.034262522330899686
  (499, 45957)	0.034262522330899686
  (499, 8851)	0.034262522330899686
  (499, 35770)	0.03426

In [10]:

cosine_similarities = linear_kernel(tfidf_matrix)

print("The Dim of cosine_similarities is: ", (cosine_similarities.shape)) 
print(cosine_similarities)


results = {}

for idx, row in ds.iterrows():
    similar_indices = cosine_similarities[idx].argsort()[:-100:-1]
    similar_items = [(cosine_similarities[idx][i], ds['id'][i]) for i in similar_indices]

    results[row['id']] = similar_items[1:]
    
print('done!')


The Dim of cosine_similarities is:  (500, 500)
[[1.         0.10110642 0.06487353 ... 0.06097409 0.06546914 0.06955608]
 [0.10110642 1.         0.4181664  ... 0.03550042 0.06936414 0.06480538]
 [0.06487353 0.4181664  1.         ... 0.03402428 0.0455137  0.05038512]
 ...
 [0.06097409 0.03550042 0.03402428 ... 1.         0.04187121 0.04958298]
 [0.06546914 0.06936414 0.0455137  ... 0.04187121 1.         0.36281626]
 [0.06955608 0.06480538 0.05038512 ... 0.04958298 0.36281626 1.        ]]
done!


In [8]:

print("The Dim of results is: ", len(results)) 
print(results)

The Dim of results is:  500
{1: [(0.22037921472617467, 19), (0.16938950913002365, 494), (0.16769458065321555, 18), (0.1648552774562297, 172), (0.1481261546058637, 442), (0.14577863284367548, 171), (0.14137642365361247, 21), (0.13884463426216961, 495), (0.1387953333136303, 25), (0.13813550299091382, 496), (0.13481110970996824, 487), (0.13225329613833617, 20), (0.13028260329762037, 341), (0.1276874354010326, 176), (0.12671622868413676, 488), (0.1231962366064138, 365), (0.12155681060658875, 340), (0.11800704948227385, 60), (0.11786722607586671, 440), (0.11657908072337499, 497), (0.11184896270837241, 173), (0.11069752245804715, 441), (0.10857685392562931, 413), (0.10572078621963335, 443), (0.10553058093119759, 174), (0.10403103809186273, 359), (0.10338035552770777, 22), (0.10290746221687944, 61), (0.10286246471301802, 312), (0.10166673618893798, 23), (0.10110641701157388, 2), (0.10082418508282533, 360), (0.09914029968349487, 175), (0.09882976519938345, 329), (0.09677082647987272, 24), (0.0

In [9]:
cosine_similarities2 = cosine_similarity(tfidf_matrix)

results1 = {}

for idx, row in ds.iterrows():
    similar_indices = cosine_similarities2[idx].argsort()[:-100:-1]
    similar_items = [(cosine_similarities2[idx][i], ds['id'][i]) for i in similar_indices]

    results1[row['id']] = similar_items[1:]
    
print('done!')

done!


In [11]:

def item(id):
    return ds.loc[ds['id'] == id]['description'].tolist()[0].split(' - ')[0]

# Just reads the results out of the dictionary.
def recommend(item_id, num):
    print("Recommending " + str(num) + " products similar to " + item(item_id) + "...")
    print("-------")
    recs = results[item_id][:num]
    for rec in recs:
        print("Recommended: " + item(rec[1]) + " (score:" + str(rec[0]) + ")")



In [12]:
recommend(item_id=11, num=5)

Recommending 5 products similar to Baby sunshade top...
-------
Recommended: Sunshade hoody (score:0.21330296021085024)
Recommended: Baby baggies apron dress (score:0.10975311296284812)
Recommended: Runshade t-shirt (score:0.09988151262780731)
Recommended: Runshade t-shirt (score:0.09530698241688207)
Recommended: Runshade top (score:0.08510550093018411)


In [13]:

def item(id):
    return ds.loc[ds['id'] == id]['description'].tolist()[0].split(' - ')[0]

# Just reads the results out of the dictionary.
def recommend1(item_id, num):
    print("Recommending " + str(num) + " products similar to " + item(item_id) + "...")
    print("-------")
    recs = results1[item_id][:num]
    for rec in recs:
        print("Recommended: " + item(rec[1]) + " (score:" + str(rec[0]) + ")")


In [14]:
recommend1(item_id=11, num=5)

Recommending 5 products similar to Baby sunshade top...
-------
Recommended: Sunshade hoody (score:0.2133029602108503)
Recommended: Baby baggies apron dress (score:0.10975311296284804)
Recommended: Runshade t-shirt (score:0.09988151262780731)
Recommended: Runshade t-shirt (score:0.09530698241688208)
Recommended: Runshade top (score:0.08510550093018408)
